// <auto-generated />
using BooksDestination.Data;
using BooksDestination.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BooksDestination.Migrations
{
    [DbContext(typeof(BooksDestinationDbContext))]
    partial class BooksDestinationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BooksDestination.Model.BookRepo", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.HasKey("BookId");

                    b.ToTable("BookRepo");
                });

            modelBuilder.Entity("BooksDestination.Model.Journals", b =>
                {
                    b.Property<int>("JournalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("JName")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("JSubject")
                        .IsRequired();

                    b.Property<int>("Jtype");

                    b.HasKey("JournalId");

                    b.ToTable("Journals");
                });
#pragma warning restore 612, 618
        }
    }
}
